//
//  main.swift
//  AutomateZFile
//
//  Created by Stijn on 25/02/2019.
//  Copyright © 2019 dooz. All rights reserved.
//

import Foundation
import SignPost

let signPost = SignPost.shared

do {
    
    let dispatchGroup = DispatchGroup()

    
    signPost.message("🧙‍♂️ Running Sourcery for ZFile from main.swift")
    let sourceryWorker = try ZFileSourceryWorker(signPost: signPost)
    
   sourceryWorker.workers.forEach {
        dispatchGroup.enter()
        $0.attempt {
            do {
                let output = try $0()
                signPost.verbose("\(output.joined(separator: "\n"))")
            } catch {
                signPost.error("\(error)")
            }
            dispatchGroup.leave()
        }
    }
    
    dispatchGroup.notify(queue: DispatchQueue.main) {
        signPost.message("🧙‍♂️ ✅ output can be found at \n\(sourceryWorker.autoGeneratedCodeFolder.path)\n🧙‍♂️")
        exit(EXIT_SUCCESS)
    }
    dispatchMain()
} catch {
    signPost.error("❌\n\(error)\n❌")
    exit(EXIT_FAILURE)
}
