//
//  main.swift
//  AutomateZFile
//
//  Created by Stijn on 25/02/2019.
//  Copyright © 2019 dooz. All rights reserved.
//

import Foundation
import SignPost

let signPost = SignPost.shared


do {
    signPost.message("🧙‍♂️ Running Sourcery for ZFile from main.swift")
    let sourceryWorker = try ZFileSourceryWorker(signPost: signPost)
    try sourceryWorker.attempt()
    signPost.message("🧙‍♂️ ✅ output can be found at \n\(sourceryWorker.autoGeneratedCodeFolder.path)\n🧙‍♂️")
} catch {
    signPost.error("❌\n\(error)\n❌")
}
