//
//  DemoSourceryWorker.swift
//  Automate
//
//  Created by Stijn on 16/12/2018.
//  Copyright © 2018 dooz. All rights reserved.
//

import Foundation
import SourceryAutoProtocols
import ZFile
import Terminal
import SourceryWorker
import SignPost
import Arguments

protocol ZFileSourceryWorkerProtocol {
    /// sourcery:inline:DemoSourceryWorker.AutoGenerateProtocol
    
    
    /// sourcery:end
}

class ZFileSourceryWorker: ZFileSourceryWorkerProtocol, AutoGenerateProtocol {
    
    static let rootFolderPrefix: String = "--rootFolder:"
    
    var autoGeneratedCodeFolder: FolderProtocol?
    var workers: [SourceryWorkerProtocol]?
    
    private let disk: DiskProtocol
    private let signPost: SignPostProtocol
    private static let commonImportAutoMockable = Set([
        TemplatePrepend.Import(name: "SourceryAutoProtocols"),
        TemplatePrepend.Import(name: "Foundation"),
        TemplatePrepend.Import(name: "os"),
        ])
    
    enum Target: String, CaseIterable {
        case ZFile
        case AutomateZFile
        case FoundationGenericHelper
        
        func imports() -> Set<TemplatePrepend> {
            
            // Insert the target itself
            var importNames = ZFileSourceryWorker.commonImportAutoMockable
            importNames.insert(TemplatePrepend.Import(name: self.rawValue))
            importNames.insert(TemplatePrepend.Import(name: VendorFramework.FoundationGenericHelper.rawValue))
            
            // If not the default, add a case and insert imports into importNames
            switch self {
            default:
                return Set([TemplatePrepend(name: importNames, template: Template.AutoMockable.rawValue)])
            }
        }
    }
    
    enum VendorFramework: String, CaseIterable {
        case ZFile
        case FoundationGenericHelper
    }
    
    enum Template: String {
        case AutoMockable
    }
    
    init(
        disk: DiskProtocol,
        signPost: SignPostProtocol = SignPost.shared
        ) throws {
        self.signPost = signPost
        self.disk = disk
    }
    
    /// Best to do this on a background queue
    public func attemptCreateWorkers() throws  {
        let projectFolder = try disk.srcRoot.subfolder(named: "Sources/ZFile")
        
        let sourcesFolder = try projectFolder.subfolder(named: "Sources")
        
        let highwayFolder = try disk.carthage.checkouts.subfolder(named: "highway")
        let templateFolder = try disk.carthage.checkouts.subfolder(named: "template-sourcery/Sources/stencil")
        let sourceryAutoProtocolFile = try highwayFolder.file(named: "/Sources/highway/Sources/SourceryAutoProtocols/SourceryAutoProtocols.swift")
        let autoGeneratedCodeFolder = try projectFolder.createSubfolderIfNeeded(withName: "Sources/AutoGeneratedCode")
        let sourceryExecutableFile = try SourceryBuilder().attemptToBuildSourceryIfNeeded()
        
        let sourcerySequence = try Target.allCases.map { target in
            return try Sourcery(
                sourcesFolders: [sourcesFolder.subfolder(named: target.rawValue)],
                individualSourceFiles: nil,
                templateFolder: templateFolder,
                outputFolder: try autoGeneratedCodeFolder.createSubfolderIfNeeded(withName: target.rawValue),
                sourceryAutoProtocolsFile: sourceryAutoProtocolFile,
                sourceryYMLFile: try projectFolder.createFileIfNeeded(named: ".sourcery-\(target.rawValue).yml"),
                imports: target.imports(),
                sourceryExecutableFile: sourceryExecutableFile
            )
        }
        
        try sourcerySequence.forEach {
            signPost.verbose("""
                > \($0.sourceryYMLFile.path)
                
                ```yml
                \(try $0.sourceryYMLFile.readAsString())
                ```
                
                """
            )
        }
        
        self.autoGeneratedCodeFolder = autoGeneratedCodeFolder
        self.workers =  try sourcerySequence.map { try SourceryWorker(sourcery: $0) }
        
    }
    // MARK: - Error
    
    enum Error: Swift.Error {
        case noCommandlineArgumentForRootFolder
    }
}
