// swift-tools-version:4.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "ZFile",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "ZFile",
            targets: ["ZFile"]),
        .library(
            name: "ZFileMock",
            targets: ["ZFileMock"]),
        .library(
            name: "FoundationGenericHelper",
            targets: ["FoundationGenericHelper"])
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/doozMen/highway", from: "2.0.23"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "ZFile",
            dependencies: ["SourceryAutoProtocols", "FoundationGenericHelper"],
            path: "Sources/ZFile/Sources/ZFile"
        ),
        .target(
            name: "ZFileMock",
            dependencies: ["ZFile", "FoundationGenericHelper", "SignPost"],
            path: "Sources/ZFile/Sources/AutoGeneratedCode/ZFile"
        ),
        .target(
            name: "FoundationGenericHelper",
            dependencies: [],
            path: "Sources/ZFile/Sources/FoundationGenericHelper"
        ),
        .testTarget(
            name: "ZFileTests",
            dependencies: ["ZFile"])
    ]
)
