//
//  DemoSourceryWorker.swift
//  Automate
//
//  Created by Stijn on 16/12/2018.
//  Copyright © 2018 dooz. All rights reserved.
//

import Foundation
import SourceryAutoProtocols
import ZFile
import Terminal
import SourceryWorker
import SignPost
import Arguments

protocol ZFileSourceryWorkerProtocol {
    /// sourcery:inline:DemoSourceryWorker.AutoGenerateProtocol
    
    
    /// sourcery:end
}

class ZFileSourceryWorker: ZFileSourceryWorkerProtocol, AutoGenerateProtocol {
    
    static let rootFolderPrefix: String = "--rootFolder:"
    
    let dependencies: SwiftPackageDependenciesProtocol
    var autoGeneratedCodeFolder: FolderProtocol?
    var workers: [SourceryWorkerProtocol]?
    let sourceryBuilder: SourceryBuilderProtocol
    let dump: SwiftPackageDumpProtocol
    
    private let signPost: SignPostProtocol
    
    init(
        dependencies: SwiftPackageDependenciesProtocol,
        dump: SwiftPackageDumpProtocol,
        sourceryBuilderType: SourceryBuilderProtocol.Type = SourceryBuilder.self
        signPost: SignPostProtocol = SignPost.shared
    ) throws {
        self.signPost = signPost
        self.dependencies = dependencies
        self.dump = dump
        self.sourceryBuilder = sourceryBuilderType.init
    }
    
    /// Best to do this on a background queue
    public func attemptCreateWorkers() throws  {
       
        
        let sourcerySequence = try ["ZFile", "ZFileMock"].map { productName in
            return try Sourcery(
                productName: productName,
                swiftPackageDependencies: dependencies,
                swiftPackageDump: dump,
                sourceryExecutable: <#T##FileProtocol#>)
        }
        
        try sourcerySequence.forEach {
            signPost.verbose("""
                > \($0.sourceryYMLFile.path)
                
                ```yml
                \(try $0.sourceryYMLFile.readAsString())
                ```
                
                """
            )
        }
        
        self.autoGeneratedCodeFolder = autoGeneratedCodeFolder
        self.workers =  try sourcerySequence.map { try SourceryWorker(sourcery: $0) }
        
    }
    // MARK: - Error
    
    enum Error: Swift.Error {
        case noCommandlineArgumentForRootFolder
    }
}
